### ISSUE TITLE
JsonWebTokenError - Issue using Secret Key

### ISSUE THREAD

**Issue by VisweshK** [camicroscope/Distro#185]
**Bug Descriptions**
Created the credentials from the linked guide and edited the client id in config/login.html. I also edited config/add_users.js to add a new admin user and uncommented the line to insert into the db. 

When run I'm getting the following error

<img width="1177" alt="Screen Shot 2022-01-19 at 5 06 59 PM" src="https://user-images.githubusercontent.com/31373276/150243827-db93aaf6-d569-482f-9f39-9b1745a6b72d.png">

Further it seems like it successfully signs in via the Google-sign in but then produces an error stating "User not found" and redirects to the User Signup page. 

Currently I'm unsure where the client secret key needs to be added and if the mongo db update is working to add the new user as an admin since I also see a BulkWriteError from mongo in the logs.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Safari

**Comment by birm** [comment]
Thanks for the report, and apologies that you're experiencing this issue.

The [section of code it's complaining about](https://github.com/camicroscope/Caracal/blob/f435f6fd48636281900b097150d6fd5305444296/handlers/authHandlers.js#L194) and [where it's being invoked](https://github.com/camicroscope/Caracal/blob/f435f6fd48636281900b097150d6fd5305444296/caracal.js#L72) suggests that the public/private key pair for the service itself wasn't generated, or otherwise has some issue.

If you can, please try either:
- running `<wherever you cloned distro>/jwt_keys/make_keys.sh` on your host 
-[ making this change](https://github.com/camicroscope/Distro/commit/769042815439815d99dd704617d196b534ec9225) to the docker compose file

and let us know if that resolve this issue.
